# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IonixTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IonixTest
  pod 'Alamofire'
  pod 'Kingfisher'

  target 'IonixTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IonixTestUITests' do
    # Pods for testing
  end

end
